Moved CI to GH Actions.
spirit-code/ovf pull request #14
Opened 2021-08-11 20:21 UTC by MSallermann

Replaces the travis and appveyor CI with github actions.
Includes coverage and pypi deployment and also adds windows builds, which were previously not covered.
Branched from master, since it is ahead of develop.

2021-08-11 21:33 UTC, GPMueller requested changes
Aside from the Fortran build missing, this looks very good 👍

2021-08-11 21:33 UTC, GPMueller commented on .github/workflows/ci.yml
> +        openmp: [false]
`openmp` can be removed, right?

2021-08-11 21:33 UTC, GPMueller commented on .github/workflows/ci.yml
> +      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_FLAGS
I think on the configure step, you could add
```bash
if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then export CMAKE_FLAGS=$CMAKE_FLAGS -DOVF_BUILD_FORTRAN_BINDINGS=ON; fi
```
or have different configure-steps for Ubuntu and others, like here: https://github.com/GPMueller/imgui-app/blob/main/.github/workflows/ci.yml#L21-L25

2021-08-11 21:33 UTC, GPMueller commented on .github/workflows/ci.yml
> +    - name: upload C++ coverage
nitpicking, but for readability there should be an empty line above here

2021-08-11 21:33 UTC, GPMueller commented on .github/workflows/ci.yml
> +    - name: Deploy to PyPI
This could use a "🚀" in the name 😉

2021-08-11 21:55 UTC, GPMueller commented
I'm not sure why the codecov comment and checks are missing, but I activated the coveralls comment and set a minimum of 80% coverage for success and a max. 5% coverage decrease.
I also removed the AppVeyor connection so the CI should work fine from the next run onwards.

2021-08-12 08:08 UTC, MSallermann commented
I made the requested changes. 
The test of the fortran bindings seems to fail on the debug build, however. I think this might be a genuine bug.

https://github.com/spirit-code/ovf/pull/14/checks?check_run_id=3309330205
```
At line 118 of file /home/runner/work/ovf/ovf/fortran/ovf.f90
5: Fortran runtime error: Substring out of bounds: upper bound (72) of 'f_ptr' exceeds string length (0)
```

2021-08-12 10:59 UTC, GPMueller approved these changes

2021-08-12 15:55 UTC, GPMueller requested changes
Looks like coveralls should be called a little differently. Right now, it is also calculating the coverage of the `python/test` folder: https://coveralls.io/github/spirit-code/ovf?branch=gh_actions
Looking at https://github.com/spirit-code/spirit/blob/develop/.github/workflows/ci.yml#L117-L126, I think the `coverage` call should be
```
coverage run --source ovf --omit=ovf/ovflib.py setup.py test > cov.txt
```

2021-08-14 21:58 UTC, GPMueller approved these changes

2021-08-18 10:23 UTC, merged